/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastane_otomasyonu;

import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author faruk
 */
public class Kayit_Ekrani extends javax.swing.JFrame {

	Ana_Ekran anaEkran = new Ana_Ekran();
	Hastane hastane = anaEkran.hastane;
	String gender = null;
	List<Hasta> hastaList = hastane.getHastaList();
	public Kayit_Ekrani() 
	{
		initComponents();
		yas_secim.setValue(10);
		erkek.setSelected(true);
		gender = "Erkek";
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        erkek = new javax.swing.JCheckBox();
        kadin = new javax.swing.JCheckBox();
        kayıtOl = new javax.swing.JButton();
        kayit_tc = new javax.swing.JTextField();
        anaEkranaDon = new javax.swing.JButton();
        ad_txt = new javax.swing.JTextField();
        yas_secim = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        soyad_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Soyad");

        jLabel2.setText("TC");

        jLabel3.setText("Yas");

        jLabel4.setText("Cinsiyet");

        erkek.setText("Erkek");
        erkek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erkekActionPerformed(evt);
            }
        });

        kadin.setText("Kadin");
        kadin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kadinActionPerformed(evt);
            }
        });

        kayıtOl.setText("KAYIT OL");
        kayıtOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıtOlActionPerformed(evt);
            }
        });

        anaEkranaDon.setText("Ana Ekran");
        anaEkranaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anaEkranaDonActionPerformed(evt);
            }
        });

        jLabel5.setText("Ad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(soyad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(erkek)
                                .addGap(18, 18, 18)
                                .addComponent(kadin)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(anaEkranaDon)
                                    .addComponent(kayıtOl)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ad_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(kayit_tc)
                            .addComponent(yas_secim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soyad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kayit_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(yas_secim, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(erkek)
                    .addComponent(kadin)
                    .addComponent(kayıtOl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(anaEkranaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private boolean hastaVar() {
		boolean hastaVar = false;
		if(hastaList != null){
			for (Hasta hasta : hastaList) {
				if (hasta.getTc() == Integer.parseInt(kayit_tc.getText())) {
					JOptionPane.showMessageDialog(rootPane, "Boyle bir hasta mevcuttur. Lutfen baska bir TC numarasi giriniz.");
					hastaVar = true;
					break;
				}
			}
		}
		
		return hastaVar;
	}
	
	private boolean isCharacterOnly(String text)
	{
		
		for (int i = 0; i < text.length(); i++) {
			if((text.charAt(i) < 'a' || text.charAt(i) > 'z')
				&&(text.charAt(i) < 'A' || text.charAt(i) > 'Z'))
			{
				return false;
			}
		}
		return true;
	}
	
	private boolean karakterVarmi(String text)
	{
		try{
		Float.parseFloat(text);
		}
		catch(NumberFormatException e)
		{
			System.out.println(e);
		return true;
		}
		return false;
	}
    
	private boolean noktaVarmi(String text){
		for (int i = 0; i < text.length(); i++) {
			if(text.charAt(i) == '.')
			{
				return true;
			}
		}
		return false;
	}
    private void kayıtOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıtOlActionPerformed
		// kayıt aşamasındaki kontroller ve kayıttaki database e ekleme işlemi
		if(Integer.parseInt(yas_secim.getValue().toString()) < 3 || Integer.parseInt(yas_secim.getValue().toString()) > 110)
		{
			JOptionPane.showMessageDialog(rootPane, "Girilen yaşa dikkat ediniz(3-110 arası olamlıdır.)");
			return;
		}
		//tc kimlik 11 haneden farklı olamaz(denemesi kolay olsun diye 1 bırakıldı)
		if(kayit_tc.getText().length() != 1){
			JOptionPane.showMessageDialog(rootPane, "TC no 11 haneden farklı olamaz");
			return;
		}
		
		if(karakterVarmi(kayit_tc.getText()) == true || noktaVarmi(kayit_tc.getText()) == true){
			JOptionPane.showMessageDialog(rootPane, "TC no alanında rakam haric bir sey bulunamaz");
			return;
		}
		
		if(ad_txt.getText().length() < 3 || soyad_txt.getText().length() < 2)
		{
			JOptionPane.showMessageDialog(rootPane, "Lütfen ad ve soyadın doğruluğundan emin olunuz.");
			ad_txt.setText("");
			soyad_txt.setText("");
			return;
		}
		
		if(!isCharacterOnly(ad_txt.getText())){
			JOptionPane.showMessageDialog(rootPane, "Ad ve Soyad kısmında rakam yada ? . ! gibi karakterler kullanılamaz");
			return;
		}
		
		//Hastanede böle bir hasta yoksa ekleme yapar
        if(!hastaVar())
		{
			Hasta hasta = new Hasta(ad_txt.getText(),soyad_txt.getText(),Integer.parseInt(kayit_tc.getText()),
									Integer.parseInt(yas_secim.getValue().toString()),gender);
			anaEkran.myDataBase.addToDatabase(hasta);
			JOptionPane.showMessageDialog(rootPane, "Kayıtınız başarıyla tamamlanmıştır.");
			this.setVisible(false);
			anaEkran.setVisible(true);
		}

    }//GEN-LAST:event_kayıtOlActionPerformed

    private void anaEkranaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anaEkranaDonActionPerformed
        // TODO add your handling code here:
		anaEkran.setVisible(true);
		this.setVisible(false);
		
    }//GEN-LAST:event_anaEkranaDonActionPerformed

    private void erkekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erkekActionPerformed
        kadin.setSelected(false);
		gender = "erkek";
    }//GEN-LAST:event_erkekActionPerformed

    private void kadinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kadinActionPerformed
        erkek.setSelected(false);
		gender = "kadın";
    }//GEN-LAST:event_kadinActionPerformed

	
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Kayit_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Kayit_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Kayit_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Kayit_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Kayit_Ekrani().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_txt;
    private javax.swing.JButton anaEkranaDon;
    private javax.swing.JCheckBox erkek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox kadin;
    private javax.swing.JTextField kayit_tc;
    private javax.swing.JButton kayıtOl;
    private javax.swing.JTextField soyad_txt;
    private javax.swing.JSpinner yas_secim;
    // End of variables declaration//GEN-END:variables
}
